package com.mashaal.ecommerce_app.ui.theme

import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.runtime.Immutable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
data class AppDimensions(
    val paddingExtraSmall: Dp = 4.dp,
    val paddingSmall: Dp = 8.dp,
    val paddingSmallInBetween: Dp = 14.dp,
    val paddingMedium: Dp = 16.dp,
    val paddingMediumInBetween: Dp = 20.dp,
    val paddingLarge: Dp = 24.dp,
    val paddingExtraLarge: Dp = 32.dp,
    val screenPaddingHorizontal: Dp = 16.dp,
    val screenPaddingVertical: Dp = 16.dp,
    val standardScreenPadding: PaddingValues = PaddingValues(16.dp),
    val spacingExtraSmall: Dp = 4.dp,
    val spacingSmall: Dp = 8.dp,
    val spacingMedium: Dp = 16.dp,
    val spacingLarge: Dp = 24.dp,
    val spacingExtraLarge: Dp = 32.dp,
    val buttonHeight: Dp = 60.dp,
    val buttonCornerRadius: Dp = 19.dp,
    val cardCornerRadius: Dp = 18.dp,
    val cardSmallCornerRadius: Dp = 8.dp,
    val productItemCornerRadius: Dp = 18.dp,
    val searchBarHeight: Dp = 50.dp,
    val searchBarCornerRadius: Dp = 15.dp,
    val bottomNavCornerRadius: Dp = 15.dp,
    val iconSize: Dp = 24.dp,
    val iconSizeSmall: Dp = 20.dp,
    val iconSizeMedium: Dp = 24.dp,
    val iconSizeLarge: Dp = 28.dp,
    val productCardWidth: Dp = 175.dp,
    val productCardHeight: Dp = 250.dp,
    val categoryCardWidth: Dp = 220.dp,
    val categoryCardHeight: Dp = 170.dp,
    val bannerHeight: Dp = 160.dp,
    val elevationSmall: Dp = 2.dp,
    val elevationMedium: Dp = 4.dp,
    val elevationLarge: Dp = 8.dp,
    val logoWidth: Dp = 100.dp,
    val logoHeight: Dp = 100.dp,
    val welcomeButtonWidth: Dp = 300.dp,
    val welcomeButtonHeight: Dp = 90.dp,
    val productImageHeightLarge: Dp = 300.dp,
    val iconButtonSizeLarge: Dp = 48.dp,
    val quantityButtonSize: Dp = 40.dp,
    val quantityTextSize: Dp = 50.dp,
    val dividerThickness: Dp = 1.dp,
    val productImageHeight: Dp = 100.dp,
    val myCartProductImageHeight: Dp = 60.dp,
    val borderWidth: Dp = 1.dp,
    val borderWidthMedium: Dp = 2.dp,
    val quantityButtonContentPadding: Dp = 10.dp,
    val iconButtonSize: Dp = 45.dp,
    val categoryImageWidth: Dp = 111.dp,
    val categoryImageHeight: Dp = 75.dp,
    val categoryTextWidth: Dp = 93.dp,
    val categoryTextHeight: Dp = 44.dp,
    val indicatorWidthSmall: Dp = 8.dp,
    val indicatorWidthLarge: Dp = 24.dp,
    val indicatorHeight: Dp = 8.dp,
    val acceptedOrderImageSize: Dp = 350.dp,
    val blurEffectRadius: Float = 30f,
    val splashScreenCarrotWidth: Dp = 60.dp,
    val splashScreenCarrotHeight: Dp = 60.dp,
    val splashScreenNectarHeight: Dp = 50.dp,
    val splashScreenNectarWidth: Dp = 200.dp,
)
